image: sbtscala/scala-sbt:openjdk-18.0.2.1_1.8.1_2.13.10

stages:
  - build
  - test
  - publish


build:
  stage: build
  script:
    - sbt scalafmtSbtCheck scalafmtCheckAll compile

test:
  stage: test
  script:
    - sbt coverage test coverageReport
  artifacts:
    paths:
      - target/scala-*/scoverage-report/index.html

publish:
  stage: publish
  script:
    - sbt universal:packageBin
  artifacts:
    paths:
      - target/universal/*.zip



