image: sbtscala/scala-sbt:openjdk-18.0.2.1_1.8.1_2.13.10

stages:
  - build
  - test
  - publish


build:
  stage: build
  script:
    - sbt scalafmtSbtCheck scalafmtCheckAll compile

test:
  stage: test
  script:
    - sbt coverage test IntegrationTest/test coverageReport
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/scala-*/coverage-report/cobertura.xml

publish:
  stage: publish
  script:
    - sbt universal:packageBin
  artifacts:
    paths:
      - target/universal/*.zip
