version: "3.2"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../../mappings/news/
        target: /home/wiremock/mappings
